def game = project.findProperty("SA_GAME") ?: "sa2"
def isSa1 = game == "sa1"

apply plugin: "com.android.application"

android {
    namespace "org.libsdl.app"
    compileSdkVersion 34

    defaultConfig {
        applicationId isSa1 ? "com.ylports.sonicadvance1" : "com.ylports.sonicadvance2"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 8
        versionName "0.1.0-alpha8"

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["src/main/jniLibs"]
        }
    }

    lint {
        abortOnError false
    }
}

dependencies {
}
